### PR TITLE
V7 : add Vue option

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/issues/10575

### CODE REVIEW

**Comment by SudharakaP** [comment]
@pascalgrimaud : This one is ready to be merged after the generator does a new release right?

**Comment by pascalgrimaud** [comment]
exact @SudharakaP :)

**Comment by pascalgrimaud** [comment]
FYI, @SudharakaP I convert this PR to draft, so we won't merge it by mistake

**Comment by SudharakaP** [comment]
@pascalgrimaud : Sure go ahead. I added the "Status: Waiting for Generator" label for this reason, but draft works as well. :smile:

**Comment by SudharakaP** [comment]
@pascalgrimaud : Could this be merged now that v7 is released or should we wait for a more stable release? 😄

**Comment by pascalgrimaud** [comment]
@SudharakaP : only for final release, so we should wait

**Pull request merged**
