### PR TITLE
Add prettier-java to the Project for Proper Formatting

### PR DESCRIPTION
**Pull request by SudharakaP**
This adds prettier-java to the project for better formatting of java files (Thanks for reminding @pascalgrimaud 😄)

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
You need to add the pre commit hook too

**Comment by SudharakaP** [comment]
> You need to add the pre commit hook too

@pascalgrimaud : Isn't the pre-commit hook already added via `.huskyrc`? When I commit, I see the following log; 

```
husky > pre-commit (node v12.16.3)
Stashing changes... [started]
Stashing changes... [skipped]
→ No partially staged files found...
Running linters... [started]
Running tasks for {,src/**/}*.{md,json,ts,css,scss,yml} [started]
prettier --write [started]
prettier --write [completed]
git add [started]
git add [completed]
Running tasks for {,src/**/}*.{md,json,ts,css,scss,yml} [completed]
Running linters... [completed]
```

**Comment by pascalgrimaud** [comment]
Oh I see, prettier format applies for modified files, not existing ones.
So for this PR you need to launch manually npm run prettier:format

Then, in your logs, there is missing *.java too

**Comment by SudharakaP** [comment]
> Oh I see, prettier format applies for modified files, not existing ones.
> So for this PR you need to launch manually npm run prettier:format
> 
> Then, in your logs, there is missing *.java too

@pascalgrimaud : I've run prettier for the whole project and also added the missing part to include `java` when run prettier automatically on git commits. 

```
husky > pre-commit (node v12.16.3)
Stashing changes... [started]
Stashing changes... [skipped]
→ No partially staged files found...
Running linters... [started]
Running tasks for {,src/**/}*.{md,json,yaml,yml,java,ts,js,css,scss} [started]
prettier --write [started]
prettier --write [completed]
git add [started]
git add [completed]
```

**Review by pascalgrimaud — APPROVED** [review]

**Pull request merged**
