### PR TITLE
Improve Test Coverage - JHipsterService

### PR DESCRIPTION
**Pull request by Strat1987**
Related to #213

### CODE REVIEW

**Comment by SudharakaP** [comment]
@Strat1987 : Same thing happening here as mentioned by pascal; https://github.com/jhipster/jhipster-online/pull/247#issuecomment-708009899

**Comment by roexber** [comment]
@SudharakaP signed with the corresponding username now

**Comment by SudharakaP** [comment]
> @SudharakaP signed with the corresponding username now

@Strat1987 : Thanks it looks good; can you re-base and run prettier on the files; `npm run prettier:format` so that the formatting is done properly. 😄

**Comment by roexber** [comment]
@SudharakaP I did run prettier myself but it seems to differ from what's on master

**Comment by SudharakaP** [comment]
> @SudharakaP I did run prettier myself but it seems to differ from what's on master

@Strat1987 : Hmm.... I am not sure why it changes when you run prettier. Did you run it through `npm run prettier:format` or did it run automatically when you committed? But on another note, there's a compilation error since it seems that you've used the `runProcess` method in the tests but I think it's private. Could you please correct that? 😄

**Comment by SudharakaP** [comment]
@Strat1987 : Its some minor changes, so I can do it too if you could give me the permission to modify the PR. 

image

**Comment by roexber** [comment]
all should be well this time around

**Review by SudharakaP — APPROVED** [review]

**Comment by SudharakaP** [comment]
> all should be well this time around

@roexber : Thanks a lot for the contribution; it's really helpful and makes our test suite much better. 😄

**Comment by roexber** [comment]
Thank you, I'll try my best to squeeze in some more.

**Comment by SudharakaP** [comment]
You are welcome. 🙃

**Pull request merged**
