### PR TITLE
Fixed Sonar Bugs and some Criticals

### LINKED ISSUE #209: Fix and Improve SonarCloud Analysis
Improve and fix the issues reported by SonarCloud; https://sonarcloud.io/dashboard?id=jhipster_jhipster-online

### PR DESCRIPTION
**Pull request by nomuna**
- removed tests from coverage, and analysis
- removed dtos and domain classes from redundancy check
  since sonar reports common fields in entities/dtos as redundancy
- made sonar ignore some useful comments using // NOSONAR marking
- removed commented out codes
- removed / refactored cases of logging and throwing exceptions
- TODO comment wrapped in multiline/javadoc comment so that
  sonar does not see it as commented out code
- Refactored some fields and their getters and setters to
  conform Java Language Conventions
- replaced switch with map lookup and lambda call to reduce
  the cyclomatic complexity of alert-error.component.ts

Fix #209
Fix https://github.com/jhipster/jhipster-online/issues/312

### CODE REVIEW

**Comment by nomuna** [comment]
Sorry @SudharakaP ,

I removed the remote branch on my fork after rebasing to include changes from upstream... It was a mistake. 

I hope you were not working on it at the time.

**Comment by mraible** [comment]
@SudharakaP can this be merged?

**Comment by nomuna** [comment]
Hi @mraible,

I updated my fork. Tests are still running on windows.

```sh
mvn sonar:sonar
```

is running out of the box on my Windows 10 machine with Java 17.0.2.

_sonar-scanner_ (installed globally with npm) used to work out of the box too, but apparently the new version does some additional checks and fails if you do not specify the path to the java binaries.

I had to do the following change locally in the file _sonar-project.properties_.
 
```
sonar.sources=src/main/
sonar.java.binaries=./target/classes  #<-- this is new
sonar.host.url=http://localhost:9001
```

_sonar-scanner_ also will not find the test result for the client and fail.

So for _sonar-scanner_ I had to 

- make the change above in _sonar-project.properties_
- run the client tests with

```
npm test
```

and then run _sonar-scanner_ at the end.

**Comment by deepu105** [comment]
@jdubois @DanielFran this looks like some good improvements, WDYT?

**Review by jdubois — APPROVED** [review]

**Comment by jdubois** [comment]
Yes, this looks good, thanks @nomuna ! I'm going to merge this for today's release.

**Pull request merged**
