### PR TITLE
Add workflow Scope to User Token

### PR DESCRIPTION
**Pull request by SudharakaP**
This adds the workflow token to user token along with refactoring code to remove the bot token which is no longer used.

Related to https://github.com/jhipster/jhipster-online/issues/241

### CODE REVIEW

**Comment by jdubois** [comment]
Ah, I did the same as you @SudharakaP -> let me merge your PR (you did first!) and add the documentation I just wrote in another PR

**Comment by SudharakaP** [comment]
> Ah, I did the same as you @SudharakaP -> let me merge your PR (you did first!) and add the documentation I just wrote in another PR

Sorry, for the duplicate effort. 😢

**Comment by jdubois** [comment]
No problem @SudharakaP as it's better to test this twice, it's tricky...
I updated the documentation on https://github.com/jhipster/jhipster-online/commit/c9d3c3ed76cac6eaf76a2d2ff2e08af642ab83fd and I hope that's ok for you

**Comment by SudharakaP** [comment]
@jdubois : Wonderful. Thanks for letting me know. I'll do a new release with the changes soon. 😄

**Pull request merged**
