### PR TITLE
add user-agent header in the POST API call to Gitlab

### LINKED ISSUE #93: Jhipster Online can't access Gitlab repositories
I previously gave JHI Online access to my github account.  
It worked well but when I tried to plug it to my gitlab account it returned the following error :
`JHipster has failed to reach your Gitlab repositories.`

However when I go to my gitlab settings I'm seeing jhipster in my authorized apps

Do you have any clue about this error?

### PR DESCRIPTION
**Pull request by vishal423**
Closes #93

### CODE REVIEW

**Comment by vishal423** [comment]
The builds are failing due to incompatible `node.js` version forced by `generator-jhipster` dependency. This should be handled in the upgrade PR, so, I am not doing any change here.

>error generator-jhipster@6.9.0: The engine "node" is incompatible with this module. Expected version ">=10.20.1". Got "10.16.3"

**Comment by vishal423** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/19243

**Comment by pascalgrimaud** [comment]
@vishal423 : approved

**Comment by vishal423** [comment]
thanks @pascalgrimaud

**Pull request merged**
