### PR TITLE
Fixed Sonar Bugs and some Criticals

### LINKED ISSUE #209: Fix and Improve SonarCloud Analysis
Improve and fix the issues reported by SonarCloud; https://sonarcloud.io/dashboard?id=jhipster_jhipster-online

### PR DESCRIPTION
**Pull request by nomuna**
- removed tests from coverage, and analysis
- removed dtos and domain classes from redundancy check
  since sonar reports common fields in entities/dtos as redundancy
- made sonar ignore some useful comments using // NOSONAR marking
- removed commented out codes
- removed / refactored cases of logging and throwing exceptions
- TODO comment wrapped in multiline/javadoc comment so that
  sonar does not see it as commented out code
- Refactored some fields and their getters and setters to
  conform Java Language Conventions
- replaced switch with map lookup and lambda call to reduce
  the cyclomatic complexity of alert-error.component.ts

Fix #209

### CODE REVIEW

**Comment by nomuna** [comment]
Hi @atomfrede,

Could you please trigger the pipeline? Like in the other PR?

Thanks,

nomuna

**Comment by SudharakaP** [comment]
@nomuna : Sorry for taking some time to respond. I'll take a look at this soon; and hopefully we can merge. 😉

**Comment by SudharakaP** [comment]
@nomuna : I don't understand. Why did you close this PR? 🤔 🙂

**Comment by SudharakaP** [comment]
Just saw, https://github.com/jhipster/jhipster-online/pull/316#issuecomment-920043336; so no worries. 👍🏽

**Pull request closed without merging**
