### PR TITLE
Allow anonymous users to download zipfile

### LINKED ISSUE #162: Allow anonymous user to generate an application via user interface
Should be done after #160

### PR DESCRIPTION
**Pull request by swarajsaaj**
Remove security on "/download-application" and refactor user-interface
to allow non-logged in users to generate and download the zip file.

Fix #162

### CODE REVIEW

**Comment by vishal423** [comment]
@SudharakaP , I am pretty much occupied at moment and wouldn't be able to justify this review.

**Comment by SudharakaP** [comment]
> @SudharakaP , I am pretty much occupied at moment and wouldn't be able to justify this review.

Not to worry, I'll do this this week. 😄

**Review by SudharakaP — COMMENTED** [review]
@swarajsaaj : Thanks. Seems to work perfectly. 👍🏽

**Comment by swarajsaaj** [comment]
Thanks for review @SudharakaP  :)

**Comment by SudharakaP** [comment]
@swarajsaaj : You are welcome; please submit the invoice for the bounty as described at, https://www.jhipster.tech/bug-bounties/#-bug-bounties

**Comment by swarajsaaj** [comment]
bounty claimed at https://opencollective.com/generator-jhipster/expenses/42422

**Comment by pascalgrimaud** [comment]
@swarajsaaj : approved

**Comment by gmarziou** [comment]
@SudharakaP do you monitor generation stats to see if anonymous users increased number of generations?

**Comment by SudharakaP** [comment]
@gmarziou : You mean differentiate between stats for apps generated by anonymous users vs logged in users. I don't think we specifically count generations by anonymous users. Do you think we should add that as a separate stat ? 🤔

**Comment by gmarziou** [comment]
It could be interesting to see what our users prefer.

**Pull request merged**
