### PR TITLE
Upgrade generator-jhipster version to 6.10.1

### PR DESCRIPTION
**Pull request by SudharakaP**
This updates the jhipster generator to version 6.10.1

Fixes https://github.com/jhipster/jhipster-online/issues/228

### CODE REVIEW

**Review by pascalgrimaud — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
I usually update this part, at each release. Don't know why I forget this, sorry.
So it's my fault

**Comment by SudharakaP** [comment]
> I usually update this part, at each release. Don't know why I forget this, sorry.
> So it's my fault

@pascalgrimaud : No worries. I was thinking we need to add a checkbox to remind people to update jhipster-online if applicable when creating pull requests? I mean somewhere here;  https://github.com/jhipster/generator-jhipster/blob/master/.github/PULL_REQUEST_TEMPLATE.md 👍🏼

**Comment by pascalgrimaud** [comment]
yes we could, it's better than nothing
But we need to have a second check to help our contributors :)

**Comment by SudharakaP** [comment]
@pascalgrimaud : What do you mean by a second check? 😃

**Comment by SudharakaP** [comment]
@pascalgrimaud : I've added a small line in our Pull request template. Let me know what you mean by a second check please? 😄

**Comment by pascalgrimaud** [comment]
by second check, I mean a second checkbox, sorry lol

**Pull request merged**
