### PR TITLE
Upgrade jdl studio

### PR DESCRIPTION
**Pull request by deepu105**
Related to https://github.com/jhipster/jdl-studio/pull/152

### CODE REVIEW

**Comment by jdubois** [comment]
@deepu105 I'm waiting for https://github.com/jhipster/jdl-studio/actions to have a successful build first :-)

**Comment by deepu105** [comment]
@jdubois it will probably fail since the auto update of JH online part will fail since the JDL studio sub module needs to rebased and thats not gonna work there, so we need to do the update manually this one time

**Comment by deepu105** [comment]
The last job fails but if you look at the logs it failed since there is no file changes to deploy and its ok

**Comment by jdubois** [comment]
@deepu105 oh yes that's a crazy "error" message!

**Review by jdubois — APPROVED** [review]

**Comment by deepu105** [comment]
how long does it take for jhipster online to get re deployed? i need to check if everything works fine since a lot of paths changed in JDL studio

**Comment by jdubois** [comment]
I need to do a release for this, I'd say about 10 minutes... I'll ping you by chat so we can cooperate on this

**Pull request merged**
