### PR TITLE
Upgrade generator-jhipster@6.10.3

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Not sure if it's enough ?

### CODE REVIEW

**Comment by SudharakaP** [comment]
@pascalgrimaud : I think we need to upgrade the generator version in `package.json` as well; which I've done. 😄

**Comment by deepu105** [comment]
Does microservices generation work yet?

**Comment by pascalgrimaud** [comment]
I don't understand your question @deepu105

**Comment by deepu105** [comment]
I mean does generating microservices with JDL work in Jhipster online? Last time I tried it didn't

**Comment by pascalgrimaud** [comment]
I don't think so. With JH Online, you must fill the form for generating an application. You can't generate from scratch with a JDL file

**Comment by SudharakaP** [comment]
@pascalgrimaud @deepu105 : Do you guys think this is important to add? I can try adding it; maybe we should create a new issue for this? 😄

**Comment by pascalgrimaud** [comment]
I personally don't use JHipster Online, I'd prefer to use cli, so I don't have an opinion on this

**Comment by deepu105** [comment]
I don't know if its important. I was just curious

**Pull request merged**
