### PR TITLE
Improve Test Coverage - EntityStatColumn, CiCdToolTest, SubGenEventTypeTest

### PR DESCRIPTION
**Pull request by KaziNizamul**
`Task Description:`
This PR is an attempt to increase some code coverage percentage.
I added a few test cases, which made some improvement in the code coverage i.e. 78% -> 80%.

`Issue Id`:
https://github.com/jhipster/jhipster-online/issues/213

`Screenshots:`
| Earlier | Now |
--- | ---
|before_change_0 1|overall_change_6|

`Affected Files:`
- src/main/java/io/github/jhipster/online/domain/enums/EntityStatColumnTest.java
- src/main/java/io/github/jhipster/online/domain/enums/SubGenEventTypeTest.java
- src/main/java/io/github/jhipster/online/service/enums/CiCdToolTest.java

### CODE REVIEW

**Comment by KaziNizamul** [comment]
Hi @pascalgrimaud @deepu105 

the CI pipeline is failing due to lint error,
but if i am running the same in IDE, its giving me no error.
Screenshot 2023-11-02 at 6 38 45 PM


I really want to contribute to this repo.
Kindly guide..

**Comment by KaziNizamul** [comment]
> Hi @pascalgrimaud @deepu105
> 
> the CI pipeline is failing due to lint error, but if i am running the same in IDE, its giving me no error. Screenshot 2023-11-02 at 6 38 45 PM
> 
> I really want to contribute to this repo. Kindly guide..

its resolved now ! @pascalgrimaud @deepu105 
thankyou so much

**Comment by KaziNizamul** [comment]
Hi @DanielFran 
Can you kndly have a look at this PR please ..

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
Thanks @KaziNizamul for the contribution

**Pull request merged**
