### PR TITLE
add link to open the generated app in the gitpod IDE

### PR DESCRIPTION
**Pull request by PierreBesson**

### CODE REVIEW

**Comment by agaspardcilia** [comment]
Good idea, having a way to use almost every aspect of JHipster without leaving a browser is awesome.

**Comment by colameo** [comment]
...do we really want to promote commercial products?
GitPod is a closed source product and not free...!

**Comment by jdubois** [comment]
Indeed the demo is awesome (Pierre is next to me at the moment), but I agree with @colameo 

- This is not Open Source at all
- The "free" plan is too limited to be usable (only 10 hours per month)
- They ask access to people's GitHub account, and as my projects are all public I don't understand why they would need this

I'm currently using Google Cloud Shell for the same kind of feature, and if the first point is valid (not Open Source), all the other points are OK (limits are very high, no specific access to GitHub).

**Comment by jdubois** [comment]
I'm sorry everyone, but once again I agree with @colameo here. There is no reason for us to push this non-OSS product.
Indeed, we do push some products and companies, but there are usually 2 use cases:

- Cool OSS products, typically on which we rely. The list of technologies here is too long to quote.
- Companies that sponsor us. The best example is "cuba-platform", which seems to be a JHipster competitor, and still we happily put their logo on our front page as they are bronze sponsor. (btw I'm not totally sure of what they do, I never had any contact with them! but I love to think we are sponsored by a competitor!)

Of course there is a lot of "grey area" in-between those 2 use cases, but I don't see where GitPod could fit.

Also, I'm really not a great fan of them asking for such permissions on the user's repositories. I understand that sometimes you need them (we do this for JHipster online), but here that really looks unnecessary, and not something I would like to advertise.

**Comment by PierreBesson** [comment]
Agree with this, although it's cool that we can demo JHipster fully in browser. Let's not needlessly tie ourselves to an outside service. This might confuse our users.

**Pull request closed without merging**
