### PR TITLE
Add withAdminUi prompt in the generator form

### PR DESCRIPTION
**Pull request by avdev4j**
Related to https://github.com/jhipster/generator-jhipster/pull/12738

### CODE REVIEW

**Review by SudharakaP — COMMENTED** [review]
@avdev4j : There's `package-lock.json` changes that was checked in with this commit. Is this a mistake? As I don't see any `package.json` changes included. 🤔

**Comment by avdev4j** [comment]
I believe because it has not been committed when the package.json has been modified before?

**Comment by pascalgrimaud** [comment]
this project uses yarn, not npm. That's explain why :)

**Comment by avdev4j** [comment]
you got it !

**Comment by SudharakaP** [comment]
Yep, I forgot, we use `yarn`. 😄  So I've went ahead and deleted `package-lock.json`.

**Comment by avdev4j** [comment]
thanks @SudharakaP

**Comment by SudharakaP** [comment]
@avdev4j : Could this be merged now that v7 is released?

**Comment by pascalgrimaud** [comment]
Same answer with Vue.js, we need to wait for final release :)

**Review by SudharakaP — APPROVED** [review]

**Pull request merged**
