### PR TITLE
Change Log Level to Debug

### PR DESCRIPTION
**Pull request by SudharakaP**
This is a temporary change in order to test the following issue.

Related to https://github.com/jhipster/jhipster-online/issues/184

### CODE REVIEW

**Comment by SudharakaP** [comment]
Ops, I don't know why I opened this, we don't need this as I can change it in the VM itself. :relaxed:

**Comment by deepu105** [comment]
But why? You could change the log level on the running instance via the log admin screen. @jdubois should be able to do that

**Comment by pascalgrimaud** [comment]
@deepu105 : only Julien can change it, as he's the only one with ROLE_ADMIN in JHipster Online application.
I suggested to @SudharakaP to change directly the config in GCP, and restart the application for investigating.

**Comment by SudharakaP** [comment]
> But why? You could change the log level on the running instance via the log admin screen. @jdubois should be able to do that

only Julien can change it, as he's the only one with ROLE_ADMIN in JHipster Online application.
> I suggested to @SudharakaP to change directly the config in GCP, and restart the application for investigating.

@pascalgrimaud : @deepu105 : Actually I did change it via the log admin screen. I gave my own account admin permission by changing the DB column related to my account manually. And therefore I now have admin permission as well. Sorry, didn't want to bug Julien and wanted to do it quickly. :wink:

**Pull request closed without merging**
