### PR TITLE
Release v2.21.0

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Review by jdubois — APPROVED** [review]

**Comment by jdubois** [comment]
@DanielFran I'm guessing this is all OK on your side, so I'm doing the release!

**Comment by DanielFran** [comment]
Thanks @jdubois
I wanted to be sure what were now the needed steps with the latest changes you did in the project to release a new version...
We are planning a beta.2 soon, I will then do it myself.

**Comment by jdubois** [comment]
That would be awesome, do you have access to the Google Cloud Console? Doing a release automatically updates the production, but it anything goes wrong it's nice to have this access, at least to rollback.

**Comment by DanielFran** [comment]
No, I do not think so.

**Comment by jdubois** [comment]
OK, let's chat directly 1:1 to see how we can fix this (we have some limitations on the account, unfortunately it's a personal and not a corporate account, for historical reasons)

**Pull request merged**
