### PR TITLE
Gitlab integration

### PR DESCRIPTION
**Pull request by agaspardcilia**
With this PR, JHipster online will be able to support Gitlab.
Work remain to be done on liquibase change logs. A PR is about to be submitted about that.

### CODE REVIEW

**Comment by anthonyrichir** [comment]
In application-prod.yml, there are these lines commented out:
`
#    gitlab:
#        clientId: XXX
#        clientSecret: XXX
#        host: XXX
#        redirectUri: XXX
`
Does it mean that we can make it work with an private, on-premise version of Gitlab ?

**Comment by jdubois** [comment]
@anthonyrichir yes that's the idea, we want people to be able to host their own version of JHipster Online internally, and connect it to their own GitLab instance. Would like to be a beta tester?

**Comment by anthonyrichir** [comment]
@jdubois sure, I could deploy a docker image in our environment and do some testing

**Comment by anthonyrichir** [comment]
If you can give me a brief description of what I need to do to make it work, I'll give it a try asap.

**Comment by agaspardcilia** [comment]
@anthonyrichir you just need to uncomment the gitlab configuration and add the required information. It should look like this :
```yaml
gitlab:
        clientId: <yourClientID>
        clientSecret: <youSecret>
        host: https://gitlab.com/ # put own gitlab host here
        redirectUri: http://localhost:8080/api/callback/gitlab # you might need the change http://localhost:8080 but the rest should stay like this.
```

**Comment by jdubois** [comment]
Thank you so much @anthonyrichir ! My trainees @agaspardcilia @chrisdns will do their best to help you, and I should have some time this week & next week to test (and hopefully merge!) this PR.

**Comment by anthonyrichir** [comment]
Thanks all for your feedback.
I tried to build and run the branch locally, but got a Liquibase error, I guess that it's related to the PR mentioned in the first comment ? When can we expect to this see this PR ? Is there something I can do to make it work right now ?

**Comment by ruddell** [comment]
By the way, the secrets are still visible in the commit changelog so they made need to be changed if they are important

**Comment by anthonyrichir** [comment]
@agaspardcilia yes, the database is running.
Liquibase complains about this changeset:

    <changeSet author="alexandregc (generated)" id="1529501926034-13">
        <dropUniqueConstraint constraintName="UK_89yq1d6xidffms3719h4lsu6t" tableName="jdl"/>
        <addUniqueConstraint columnNames="jdl_metadata_id" constraintName="UK_89yq1d6xidffms3719h4lsu6t" tableName="jdl"/>
    </changeSet>

Here is the exception:

    2018-06-25 20:03:31.601 ERROR 6851 --- [line-Executor-1] liquibase : classpath:config/liquibase/master.xml: config/liquibase/changelog/20180620133843_gitlab.xml::1529501926034-13::alexandregc (generated): Change Set config/liquibase/changelog/20180620133843_gitlab.xml::1529501926034-13::alexandregc (generated) failed.  Error: Cannot drop index 'UK_89yq1d6xidffms3719h4lsu6t': needed in a foreign key constraint [Failed SQL: ALTER TABLE jhonline.jdl DROP KEY UK_89yq1d6xidffms3719h4lsu6t]

For now, I commented out this changeset as it doesn't seem add anything more compared to changeset 1529501926034-6, and then it's working.

**Comment by anthonyrichir** [comment]
Looking good :+1: 

image

**Comment by anthonyrichir** [comment]
After struggling a bit, I finally pushed a project on our Gitlab, here are the issues I faced:

1. The default committer is _Jhipster Bot_ with email _jhipster-bot@users.noreply.github.com_, which is not allowed on our Gitlab. I made a fix, how can I submit it ? I fork your version of the project and then do a PR ?
2. The default commit message, which doesn't work for us because we require developers to start their commit messages with a Jira ticket. For the time being, I changed the hardcoded message in the GitService, but it would be nice to allow users to override the default message. I can also work on a solution if you want, but I'm not a frontend developer so, it might take a little more time.

**Comment by agaspardcilia** [comment]
You should wait for the PR to be merged. It should be done by tomorrow. We just need to figure out what's wrong with liquibase first as this code will be used in prod.

**Comment by PierreBesson** [comment]
@anthonyrichir Eventually you can submit a new PR once this one is merged. I think the settings you want could be changed with configuration properties and then overriden with env vars.

**Pull request merged**
