### PR TITLE
Add SonarCloud Analysis to CI

### PR DESCRIPTION
**Pull request by SudharakaP**
This adds SonarCloud analysis to CI; the analysis should be triggered for PRs as well. 

Resolves https://github.com/jhipster/jhipster-online/issues/202

### CODE REVIEW

**Comment by SudharakaP** [comment]
@pascalgrimaud : I think here the `projectKey` might be incorrect which is why the build is failing. Would you be able to check the `projectKey` in the SonarCloud UI and let me know? :smile:

**Comment by pascalgrimaud** [comment]
The project key is correct: `jhipster_jhipster-online`

The problem is related to this:
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project jhonline: Could not find the pullrequest with key 'github.event.pull_request.number': Error 404 on https://sonarcloud.io/api/alm_integration/show_pullrequest?project=jhipster_jhipster-online&pullrequestKey=github.event.pull_request.number : {"errors":[{"msg":"The pullrequest could not be found"}]} -> [Help 1]
```

Maybe remove the  ̀-Dsonar.pullrequest.key=github.event.pull_request.number \` to have something working with master branch, then, we can try to have Analyze in PR ?
For that, you should work directly in master branch :)

**Comment by SudharakaP** [comment]
@pascalgrimaud : Ops you are right. I didn't even see that message. Think I am too sleepy, will complete this tomorrow. 😄

**Comment by SudharakaP** [comment]
This is done; pull request SonarCloud analysis works fine now. I'll create separate issue(s) to improve code quality. :smile:

**Pull request merged**
