### PR TITLE
Support azure container apps

### PR DESCRIPTION
**Pull request by fangjian0423**
Some updates:

- remove dev database option
- support mongodb database
- [new blueprint](https://github.com/Azure/generator-jhipster-azure-container-apps) instead of [old one](https://github.com/Azure/generator-jhipster-azure-spring-apps).

### CODE REVIEW

**Review by hangwan97 — APPROVED** [review]

**Comment by fangjian0423** [comment]
hi team, could you tell me how to fix the prettier check issue?

I try to run `npm run prettier:format`, but it does not take effect.

**Comment by hangwan97** [comment]
> prettier

Lets try to format that locally (reformat everything) then commit to the github.

**Comment by jdubois** [comment]
Can you run `prettier --check "{,src/**/}*.{md,json,yaml,yml,java,ts,js,css,scss}"` on your machine so you can see what the issue is?

**Comment by fangjian0423** [comment]
> Can you run `prettier --check "{,src/**/}*.{md,json,yaml,yml,java,ts,js,css,scss}"` on your machine so you can see what the issue is?

hey @jdubois , after upgrade the `prettier` and `prettier-plugin-java` to the correct version (1.19.1 for prettier and 0.8.3 for prettier-plugin-java). The command you mentioned return:

```bash
> prettier --check "{,src/**/}*.{md,json,yaml,yml,java,ts,js,css,scss}"
Checking formatting...
All matched files use Prettier code style!
```

**Pull request merged**
